### ISSUE TITLE
NPC Name Mismatch

### ISSUE THREAD

**Issue by ProStashio** [Gregory-Jagermeister/Fantasy-Content-Generator#1]
Seems like when a new is generated and it's copied, I seem to get the wrong name copied to my clipboard.
However, Settlements, Taverns, Items and the like all seem fine

**Comment by Gregory-Jagermeister** [comment]
Noted will Investigate this.

**Comment by Gregory-Jagermeister** [comment]
Good News After investigating the Issue, it looked like a simple variable scope problem sorted out now will update the release now
