### ISSUE TITLE
FR - Ability to add custom data sets / generators

### ISSUE THREAD

**Issue by MykeMyke** [Gregory-Jagermeister/Fantasy-Content-Generator#3]
It would be great if there was a way to add custom data sets to existing generators, and by extension additional generators.
Note - I have seen what is available in the readme, so leaving this here to see if others thing extension is valuable.

**Comment by Gregory-Jagermeister** [comment]
Hi not sure what you mean by adding custom data sets to existing generators, in the plugin settings you can add your own nouns adjectives etc. for some of the generators already if you are talking about a generator that doesn't have a custom source section could you label which generator it might already be on the internal to-do list

**Comment by MykeMyke** [comment]
I just meant that if I have a list of taverns for example with names and descriptions in a JSON/CSV file, is there a way to read those in?

**Comment by Gregory-Jagermeister** [comment]
Its very possible to do an import and export option for CSV or JSON I wasn't aware this is what you meant I'll add it to the todo list

**Comment by Gregory-Jagermeister** [comment]
Added A new release adding in the import-export of JSON files (https://github.com/Gregory-Jagermeister/Fantasy-Content-Generator/releases/tag/1.2.1) let me know of any bugs, I will shelf the idea of custom generators for now as I'm not entirely sure how to approach the problem in Typescript yet, For now, I'm closing this FR, Have Fun!
