### ISSUE TITLE
Allocate value weighting to loot generation

### ISSUE THREAD

**Issue by MykeMyke** [Gregory-Jagermeister/Fantasy-Content-Generator#4]
It would be great to allocate weighting to the loot tables such that you could provide meta-data to call a higher / lower value haul.

This is probably system specific, so a look up with the arbitrary value index vs system could be valuable.

Example of a less slick web implementation specific to 5E: [DonJon](https://donjon.bin.sh/5e/random/#type=treasure;treasure-cr=14;treasure-loot_type=treasure_hoard)

**Comment by Gregory-Jagermeister** [comment]
Hi With my latest release You can add weights to your items via JSON have a look!
