### ISSUE TITLE
What is the command in command palette?

### ISSUE THREAD

**Issue by 0atman** [Gregory-Jagermeister/Fantasy-Content-Generator#6]
Hi, I love this plugin, but I tend to hide the app ribbon, launching commands only from hotkeys and the command palette.

I can't figure out what the command is, searching for:

- fantasy
- content
- generator
- name

etc does't show it, what is the command? Thank you so much!

**Comment by Gregory-Jagermeister** [comment]
Hi there, Glad to hear you love the plugin.

Apologies for the REALLY late response, Life has had me sidetracked and I haven't seen this project in a bit. I Get what your saying and the answer is It never really had a command as the thought never crossed my mind. However I can say that I am now adding a command into it and I should have it uploaded as a minor patch soon.

**Comment by Gregory-Jagermeister** [comment]
This is now Implemented and Live.

**Comment by 0atman** [comment]
works great, thank you so much!

**Comment by Gregory-Jagermeister** [comment]
glad to have helped.
